#ifndef _GPS_DEFS_H_
#define _GPS_DEFS_H_

#include "../16550uart_defs.h"

// =====================================
// UART ADDRESSES
// using chip #two
// =====================================
#define GPS_UART_BASE (SYSTEM_IO_UART_CHIP_BASE(2))
#define GPS_UART_ADDR_RBR _16550UART_ADDR_RBR(GPS_UART_BASE)
#define GPS_UART_ADDR_THR _16550UART_ADDR_THR(GPS_UART_BASE)
#define GPS_UART_ADDR_IER _16550UART_ADDR_IER(GPS_UART_BASE)
#define GPS_UART_ADDR_IIR _16550UART_ADDR_IIR(GPS_UART_BASE)
#define GPS_UART_ADDR_FCR _16550UART_ADDR_FCR(GPS_UART_BASE)
#define GPS_UART_ADDR_LCR _16550UART_ADDR_LCR(GPS_UART_BASE)
#define GPS_UART_ADDR_MCR _16550UART_ADDR_MCR(GPS_UART_BASE)
#define GPS_UART_ADDR_LSR _16550UART_ADDR_LSR(GPS_UART_BASE)
#define GPS_UART_ADDR_MSR _16550UART_ADDR_MSR(GPS_UART_BASE)
#define GPS_UART_ADDR_SCR _16550UART_ADDR_SCR(GPS_UART_BASE)
#define GPS_UART_ADDR_DLL _16550UART_ADDR_DLL(GPS_UART_BASE)
#define GPS_UART_ADDR_DLM _16550UART_ADDR_DLM(GPS_UART_BASE)

#endif