#ifndef _WIFI_DEFS_H_
#define _WIFI_DEFS_H_

#include "../16550uart_defs.h"


// =====================================
// UART ADDRESSES
// using chip #five
// =====================================
#define WIFI_UART_BASE (SYSTEM_IO_UART_CHIP_BASE(5))
#define WIFI_UART_ADDR_RBR _16550UART_ADDR_RBR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_THR _16550UART_ADDR_THR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_IER _16550UART_ADDR_IER(WIFI_UART_BASE)
#define WIFI_UART_ADDR_IIR _16550UART_ADDR_IIR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_FCR _16550UART_ADDR_FCR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_LCR _16550UART_ADDR_LCR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_MCR _16550UART_ADDR_MCR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_LSR _16550UART_ADDR_LSR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_MSR _16550UART_ADDR_MSR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_SCR _16550UART_ADDR_SCR(WIFI_UART_BASE)
#define WIFI_UART_ADDR_DLL _16550UART_ADDR_DLL(WIFI_UART_BASE)
#define WIFI_UART_ADDR_DLM _16550UART_ADDR_DLM(WIFI_UART_BASE)

#endif